### ISSUE TITLE
Add Facebook Open Graph and Twitter Card meta tags

### ISSUE THREAD

**Issue by shillasaebi** [Comcast/Comcast.github.io-archive#148]
With the addition of these tags, we'll have a nice preview whenever someone links to the site on social media.

Both Facebook & Twitter have apps that you can use to "explore" the tags that are returned.

Here is an example with Facebook's Open Graph debugger: https://developers.facebook.com/tools/debug/sharing/?q=www.septastats.com

Twitter's Card Validator: https://cards-dev.twitter.com/validator

**Comment by kristakhare** [comment]
Closed with #197  - yay!
