### ISSUE TITLE
Create Android section

### ISSUE THREAD

**Issue by kristakhare** [Comcast/Comcast.github.io-archive#165]
We have enough projects to warrant an Android section now. Suggestion credit to @JohnRiv

**Comment by sierikov** [comment]
Hi. I'm working on this issue. Can you please give me *Title*, *Image* and *Description* for each project that needed to be displayed in Android Section?

**Comment by kristakhare** [comment]
Hi @ArtemSer. Thank you for your help with this!
We currently have 4 projects listed under Mobile: https://comcast.github.io/#mobile-projects
With the exception of ccsplite, all are Android-related projects. So maybe it's best to just rename that section to Android-related and remove ccsplite? Then there are a few other projects to add to the new section: 
https://github.com/Comcast/CloudConnectorForAndroidThings
https://github.com/Comcast/blueprint

**Comment by sierikov** [comment]
Ok, I will revert my changes and rename Mobile in Android. For these two projects, I need **Title**, **Image** and **Description**.

**Comment by kristakhare** [comment]
Let's please skip images and just go with title and description. you can pull the description from each project's top-line description, such as: 
**Blueprint:** Blueprint is a compact framework for constructing mvp architecture within a scrollable, multi-view-type list UI. It uses the Android RecyclerView library, and currently only supports LinearLayouts

Thank you!

**Comment by sureshmangs** [comment]
I have submitted a PR, please review it.

**Comment by carlism** [comment]
Thanks so much to @ArtemSer and @sureshmangs fo pushing this issue to completion!  Hope you have a happy hacktoberfest!

**Comment by sureshmangs** [comment]
Thanks
It feels really good to contribute to open source.
