### ISSUE TITLE
Mobile Usability issues

### ISSUE THREAD

**Issue by JohnRiv** [Comcast/Comcast.github.io-archive#214]
The Google Search Console Mobile Usability report identified the following issues:

- Clickable elements too close together
- Text too small to read
- Viewport not set

Suggestions on how to address those are available at https://support.google.com/webmasters/answer/9063469#viewport_not_configured

**Comment by chrysillala** [comment]
hey, may i help you?

**Comment by carlism** [comment]
@chrysillala That would be wonderful, thanks!

**Comment by chrysillala** [comment]
> @chrysillala That would be wonderful, thanks!

hey please check https://github.com/Comcast/Comcast.github.io/pull/259
thanks

**Comment by carlism** [comment]
@chrysillala Thanks again for the contribution!
