### ISSUE TITLE
Update or remove recently contributed to metrics

### ISSUE THREAD

**Issue by kristakhare** [Comcast/Comcast.github.io-archive#230]
This section on comcast.github.io is very outdated since we no longer fork to Comcast's org before submitting PRs. Open to suggestions on how to collect the true metrics, or we can just remove it for now.

**Comment by britneywright** [comment]
@kristakhare was this meant to track contributions to comcast open source projects or contributions of comcast members to outside projects?

**Comment by kristakhare** [comment]
@britneywright the latter. But since we no longer require forks to the Comcast org before contributing to outside projects, it's quite outdated. I have https://github.com/Comcast/Comcast.github.io/pull/234 to just remove it, but open to better suggestions

**Comment by kristakhare** [comment]
@JohnRiv helped to remove that. We can reopen the issue if there's a different way of tracking contributions in the future. thanks all!
