### ISSUE TITLE
Link blog page to the Comcast.github.io landing page

### ISSUE THREAD

**Issue by shillasaebi** [Comcast/Comcast.github.io-archive#239]
Link blog page (News) to the Comcast.github.io landing page, ideally next to "About, Projects, and Contact"

https://comcast.github.io/blog

**Comment by alwinaind** [comment]
Hi I would like to contribute and work on this issue.

**Comment by Vishal260700** [comment]
@shillasaebi I have made a pull request regarding the Landing page. Please review #241

**Comment by ghost** [comment]
I will like to do it

**Comment by shillasaebi** [comment]
Thank you all. This issue is now resolved!
