### ISSUE TITLE
Add Twitter feed to homepage

### ISSUE THREAD

**Issue by shillasaebi** [Comcast/Comcast.github.io-archive#249]
Can we add a Twitter feed to this page Comcast.github.io? and make it look nice too?

Twitter accounts to follow to start:

@vinyldns
@trafficctrlcdn
@TricksterIO
@todogroup
@opensourceway
@OpenSourceOrg
@ShillaSaebi
@nithyaruff

**Comment by kevalnagda** [comment]
Do you have any design in mind?

**Comment by shillasaebi** [comment]
Sure maybe something off to the side like this below format but on the right side of the page? https://twitter.github.io

**Comment by kevalnagda** [comment]
This cannot be implemented to the right with the current flow of the website as the content is centered.
I have tried embedding a feed panel though. Please take a look and suggest any changes needed.

**Comment by carlism** [comment]
@pumpkinman008 Thanks!
