### ISSUE TITLE
Safari:  404 on https://polaris.xfinity.com/cima.js.map

### ISSUE THREAD

**Issue by OttoDahlke** [Comcast/Comcast.github.io-archive#25]
Safari 10.1.1

http://comcast.github.io

Console log:

https://polaris.xfinity.com/cima.js.map  Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by JohnRiv** [comment]
That only appears when the developer tools are open. It's up to the Polaris team to fix if they wish, not our issue.
