### ISSUE TITLE
Limit the height of the twitter feeds on index.html

### ISSUE THREAD

**Issue by carlism** [Comcast/Comcast.github.io-archive#251]
The feeds scroll quite long.  Twitter embeds have a mechanism for limiting their height.  This should apply equally to all 3 lists embedded.

**Comment by thallesbrandao** [comment]
Hey, I can do this. 

Do you have preference at a embedded height?

**Comment by carlism** [comment]
@thallesbrandao, since the height restriction causes the feed to scroll, something that roughly fits on the screen all at once.  Otherwise scrolling the page vs. the feed might get confusing.
Thanks!

**Comment by carlism** [comment]
Thanks @Venoox for the contribution.
