### ISSUE TITLE
Add contributor feed to Hacktoberfest landing page 

### ISSUE THREAD

**Issue by BrittanyIstenes** [Comcast/Comcast.github.io-archive#252]
It would be great to have the feed of contributors listed underneath the open issues with their corresponding PR count.  

Ideally we would like to have the contributors github name able to be clicked on so that we can go right to their page to contact them to send swag.

**Comment by 1arshan** [comment]
I would like to add allcontributors in README. Is that waht you need?
See https://allcontributors.org/

**Comment by BrittanyIstenes** [comment]
I would like to have the contributors to Hacktoberfest listed within in the landing page underneath the open issues.  https://comcast.github.io/hacktoberfest . We currently have them listed in the stats, but the stats are not able to be clicked on to display the contributors names/github profiles. 
![image](https://user-images.githubusercontent.com/50678820/66400471-86b3f500-e9af-11e9-8f83-cbc86007bab8.png)

**Comment by britneywright** [comment]
This is implemented now with #280
