### ISSUE TITLE
Overall stats total number of members inaccurate

### ISSUE THREAD

**Issue by shillasaebi** [Comcast/Comcast.github.io-archive#258]
The Overall Stats number at the bottom of the page is incorrect. It's showing:

Total Public Repos: 191
Total Source Repos: 114
Total Forked Repos: 14
Total Members: 100

It should show 143 total members

**Comment by NeonNature** [comment]
May I take this issue please?

**Comment by hiteda** [comment]
Is it alright if I take this?

**Comment by carlism** [comment]
Thanks for the contribution!
