### ISSUE TITLE
Create talks/presentations page linked to main site

### ISSUE THREAD

**Issue by shillasaebi** [Comcast/Comcast.github.io-archive#260]
Can we create a separate linked page to post talks/presentations related to open source at Comcast? With the same look and feel of all the other pages?
Similar to this page? https://verizon.github.io/talks/

We can label the page and category as “talks” and would like to link to the main page next to About, Blog, and Home. 

Would like to include these talks:

September 16, 2019 - Elad Nafshi
Title: Virtualizing the Access Network at Comcast
https://www.youtube.com/watch?v=IvDq8oQ3I2I

July 23, 2019 - Shilla Saebi
Title: What’s brewing and cooking in your open source community?
https://www.youtube.com/watch?v=uPqxa6chajg

July 1, 2019 - Nithya Ruff
Title: How Comcast Embraced Open Source, the Key to Success in DevOps Adoption
https://www.youtube.com/watch?v=Q84YCCItDI0

July 3, 2019 - David Grizzanti 
Title: Cloud Foundry community advisory board meeting
https://www.youtube.com/watch?v=Rzd4vNuuQbw

June 21, 2019 - Michael Winslow, Catherine Rodriguez
Title: Operating Micro-services
https://www.youtube.com/watch?v=54mCIhiz9ls

April 15, 2019 - Charlie Baum
Title: The Genesis of Cloud Foundry: Using Open Source Tools to Easily Deploy
https://www.youtube.com/watch?v=zgQN17kZinc

April 15, 2019 
Title: How Cloud is Changing Open Source - Chris Power
https://www.youtube.com/watch?v=90SHieaQ16Y

April 11, 2019 - Michael Pilquist
Title: Evolving a Streaming Platform
https://www.youtube.com/watch?v=mStYwML3JZk

January 18, 2019 - Michael Pilquist
Title: Concurrency with Cats-effect
https://www.youtube.com/watch?v=Gig-f_HXvLI

December 15, 2018 - Shilla Saebi, James Ranson
Title: Got a Need for Speed? Accelerate Your Prometheus Dashboard Using Trickster 
https://www.youtube.com/watch?v=ZO7nrX20iT0

November 29, 2018 - Nithya Ruff, Swapnil Bhartiya 
Title: Open Source at Comcast
https://www.youtube.com/watch?v=RYJhSEoWB4E

November 9, 2018 - Shilla Saebi, Per Ploug, Chad Arimura, Bonnie Chatterjee
Title: The keys to open source success for enterprise teams
https://www.youtube.com/watch?v=SaWy2IDC88I

September 15, 2018 - Shilla Saebi, David Grizzanti
Title: If There Are No Metrics, Did It Even Happen? 
https://www.youtube.com/watch?v=mfXJV9dJQoc

May 21, 2018 - John Riviello
Title: The Critical Career Path Conversation
https://www.youtube.com/watch?v=hMz6QDURQOM

March 22, 2018 - Nithya Ruff, Swapnil Bhartiya 
Title: How Comcast is embracing Open Source
https://www.youtube.com/watch?v=KK012uilLH0

January 9, 2018 - Nithya Ruff
Title: Comcast's Journey and Transformation to Open Source
https://www.youtube.com/watch?v=NAu4RFTzl3w

June 23, 2017 - Greg Otto
Title: Comcast Cloud Foundry Journey
https://www.youtube.com/watch?v=pfqSsjwCOqA

May 22, 2017 - Nithya Ruff
Title: Apache Projects and Comcast’s Journey to Open Source
https://www.youtube.com/watch?v=NwZEPfICuUE

May 11, 2017 - Shilla Saebi
Title: It's An Open Source World As We Know It
https://www.youtube.com/watch?v=Dn2YCQHM_mk

December 14, 2017 - Shilla Saebi, Nithya Ruff
Title: How Comcast Embraced Open 
https://www.youtube.com/watch?v=cHD1INLaF9o

November 23, 2017 - Paul Cleary
Title: Scala for the Rest of Us
https://www.youtube.com/watch?v=CEv9KrjTF8g

October 2, 2017 - Jearvon Dharrie
Title: Automating Cloud Security and Incident Response
https://www.youtube.com/watch?v=5B0tOZoITic

July 26, 2016 - Shilla Saebi, Allison Price
Title: SuperuserTV: Celebrating OpenStack's 6th birthday in Northern Virginia
https://www.youtube.com/watch?v=TZmRqOuMVXQ

May 20, 2015 - Comcast OpenStack Team
Title: OpenStack Superuser Awards 
https://www.youtube.com/watch?v=G0l3oeUnuoA&list=PLGdkWvB2gdJkshiUx2u6hURsppTLjin6b

**Comment by rosswhitehouse** [comment]
I'd like to help with this 👋

**Comment by shillasaebi** [comment]
Sure, that would be awesome @rosswhitehouse

**Comment by bolajiscott** [comment]
i would like to fix the needful on this as well

**Comment by shillasaebi** [comment]
please feel free, thank you!

**Comment by carlism** [comment]
@rosswhitehouse Thanks so much for the contribution!  If you'd like to make another with those linter changes we'd happily accept.
