### ISSUE TITLE
Add the below videos to the talks page

### ISSUE THREAD

**Issue by shillasaebi** [Comcast/Comcast.github.io-archive#264]
The below videos should also be added to the "Talks" page and they should be in order by date on the page just like it is now: Talks page: https://comcast.github.io/talks.html

Talk links:

September 10, 2019 - Robert O Butts
Improving Apache Traffic Control CDN Operation
https://www.youtube.com/watch?v=RRqakBpDIGY&list=PLviHc90fJpw5DLB2_krlTr8Isu_yOOVlF&index=15&t=0s

September 10, 2019 - Geoff Genz
Processing CDN Logging Events at scale
https://www.youtube.com/watch?v=e9TZ6gFDjNg&list=PLviHc90fJpw5DLB2_krlTr8Isu_yOOVlF&index=14&t=0s

September 10, 2019 - Evan Zelkowitz
Taming the Herd - Tuning ATS for Linear Video
https://www.youtube.com/watch?v=hhHtBraAEtY&list=PLviHc90fJpw5DLB2_krlTr8Isu_yOOVlF&index=12&t=0s

September 10, 2019 - Jeff Elsloo
Using Apache Traffic Control to Cache Any Web Object at Scale
https://www.youtube.com/watch?v=-0QAAzMbBlQ&list=PLviHc90fJpw5DLB2_krlTr8Isu_yOOVlF&index=10&t=0s

September 10, 2019 - Dan Kirkwood
Workshop: Getting Apache Traffic Control Up And Running
https://www.youtube.com/watch?v=GYS2mi8RkC4&list=PLviHc90fJpw5DLB2_krlTr8Isu_yOOVlF&index=9&t=0s

September 10, 2019 - Jamie Panagos
Anycast ATC Integration at Comcast
https://www.youtube.com/watch?v=sO0OEODhZYw&list=PLviHc90fJpw5DLB2_krlTr8Isu_yOOVlF&index=7&t=0s

September 10, 2019 - Matt Jackson
Let's Encrypt Apache Traffic Control
https://www.youtube.com/watch?v=6oApazcsqkE&list=PLviHc90fJpw5DLB2_krlTr8Isu_yOOVlF&index=6&t=0s

September 10, 2019 - Jonathan Gray
Automating Apache Traffic Control Deployments with Ansible
https://www.youtube.com/watch?v=aVxFNdrqZRM&list=PLviHc90fJpw5DLB2_krlTr8Isu_yOOVlF&index=5&t=0s

September 10, 2019 - Jason Tucker
Automating Apache Traffic Control Server Deployments with IPv6
https://www.youtube.com/watch?v=8rvvqSmdxtk&list=PLviHc90fJpw5DLB2_krlTr8Isu_yOOVlF&index=4&t=0s

September 10, 2019 - Dave Neuman
Welcome to the Content Delivery Track
https://www.youtube.com/watch?v=WAsRH1Cyqfo&list=PLviHc90fJpw5DLB2_krlTr8Isu_yOOVlF&index=2&t=0s

August 27, 2019 - Chris Hines
Death by 3,000 Timers: Streaming Video-on-Demand for Cable TV
https://www.youtube.com/watch?v=h0s8CWpIKdg&feature=youtu.be

April 15, 2019 - Dilleswara Anupoju
FaaS: A Contemporary
https://www.youtube.com/watch?v=vN6mLhESIi0&list=PLQ0m6qIJXFlWk2Xskv3JPsXvCAhww-O00&index=35

April 15, 2019 - Sergey Matochkin
Practical Guide to Frictionless Cloud Native Security for DevOps 
https://www.youtube.com/watch?v=PLagIq3Bxi0&list=PLQ0m6qIJXFlWk2Xskv3JPsXvCAhww-O00&index=31

April 15, 2019 - Colby Johnston, Brett Mayer
Extending Cloud Foundry at Scale
https://www.youtube.com/watch?v=H7KReZGqgmU&list=PLQ0m6qIJXFlWk2Xskv3JPsXvCAhww-O00&index=32

April 15, 2019 - Tim Leong
A Victim of Our Own Success – Overcoming the Challenges of 30,000 AIs
https://www.youtube.com/watch?v=qtxYeyxciAM&list=PLQ0m6qIJXFlWk2Xskv3JPsXvCAhww-O00&index=34

April 15, 2019 - Mike Graham, Dan Carroll
Deep Dive: Cloud Foundry Stream Processing
https://www.youtube.com/watch?v=oVvoqg-NiKU&list=PLQ0m6qIJXFlWk2Xskv3JPsXvCAhww-O00&index=33

Sep 28, 2018 - Dave Neuman
Streaming Media at Scale – The Story of How Apache Traffic Control Came To Be
https://www.youtube.com/watch?v=Ogk5PGy9ecU

**Comment by jxb04** [comment]
I would like to work on this one.

**Comment by shillasaebi** [comment]
Sure thing, thank you Joel!

**Comment by carlism** [comment]
Thanks for the contribution @ShripadMhetre
