### ISSUE TITLE
Improve the performance of the hacktoberfest stats.

### ISSUE THREAD

**Issue by carlism** [Comcast/Comcast.github.io-archive#272]
Our page on hacktoberfest pulls stats from 3 different github repos.
The page is slow to load because no rendering happens till all the api calls complete.
Ideally, the stats would be rendered progressively as they are available.
This wouldn't make the stats faster, but there would be more visual feedback that things were loading.

**Comment by coderwassananmol** [comment]
I would like to work on that.

**Comment by carlism** [comment]
@coderwassananmol, by all means, thanks!

**Comment by coderwassananmol** [comment]
Hey @carlism, do you want to show the visual feedback on the loading data or should we change the underlying code of API calls?

**Comment by carlism** [comment]
I was thinking the counts and totals would increase as the data was processed.  I realize some of them can't be evaluated until the very end.  But I think some of the totals possibly could.  I think if we just do a loading animation or something it wouldn't be much better than the ellipses that are there now.

**Comment by carlism** [comment]
Thank you @coderwassananmol  for the contribution.  The loading treatment will help.  I will be leaving the issue open in case someone wants to tackle progressive updates during the network operations.

**Comment by carlism** [comment]
Thanks for the contribution @britneywright !
