### ISSUE TITLE
Relaunch Hacktoberfest page

### ISSUE THREAD

**Issue by BrittanyIstenes** [Comcast/Comcast.github.io-archive#317]
We need to add the Hacktoberfest page back up into the site:

https://github.com/Comcast/Comcast.github.io/blob/main/hacktoberfest.html 

- Clear the contributors from last year
- Make sure all of the text says 2020 where it says 2019
- Update the image header to be: https://github.com/Comcast/Comcast.github.io/blob/main/img/hacktoberfest_logo_2020.png
- Add the page to the main site via a linked banner at the top containing this blurb "Hacktoberfest is back!  Comcast is proud to participate in the Digital Ocean Hacktoberfest initiative.  Click here to learn more"

**Comment by shillasaebi** [comment]
I've updated the banner from the 2019 one to the 2020 one. I've also updated where it says 2019 to 2020. 

The contributors from last year still need to be cleared, and the participating repos/PRs/issues need to be updated to reflect this year as well. All the stats are from last year too. 

Once the script is updated to reflect 2020 contributors, PRs/issues/ and stats, we can then link to the main page.
