### ISSUE TITLE
carousel/jobs.jpg is big

### ISSUE THREAD

**Issue by OttoDahlke** [Comcast/Comcast.github.io-archive#90]
https://comcast.github.io/img/carousel/jobs.jpg

Five times bigger than the next biggest image.

URL | Total Size | Transfer Time
…carousel/jobs.jpg | 2,671 KB | 14,640 ms
…carousel/innovation.jpg | 456 KB | 2,500 ms

**Comment by trevmex** [comment]
Fixed.
